name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 'Test code with JDK ${{ matrix.jdk }}'
    strategy:
      matrix:
        jdk: [ 8, 11 ]
    runs-on: ubuntu-20.04
    steps:
      - name: 'Cancel any previous runs'
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Cache local gradle cache'
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('build.gradle') }}
          restore-keys: |
            gradle-
      - name: 'Set up JDK ${{ matrix.jdk }}'
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'zulu'
      - name: 'Test'
        shell: bash
        run: ./gradlew test
